### ISSUE TITLE
[Examples] Add examples and list out support on homepage

### ISSUE THREAD

**Issue by mwang87** [mwang87/MetabolomicsSpectrumResolver#1]

**Comment by sdrogers** [comment]
Done?

**Comment by mwang87** [comment]
Done.

**Comment by schymane** [comment]
Documentation looks good but it's not inherently clear that users have to enter the entire string of usi=mzdata:MASSBANK:BSU00002
If you get this wrong, you just get an internal server error, which is not very informative. i.e. I think most people would think of trying e.g. BSU00002 or MASSBANK:BSU00002 but not adding the usi=mzdata: bit. Add some text or hints to make this more obvious? The examples are good, but people will have to extrapolate what to enter from the URL ... 
https://metabolomics-usi.ucsd.edu/spectrum/?usi=mzdata:MASSBANK:BSU00002
