### ISSUE TITLE
Wrong Error 500 for not-found spectrum

### ISSUE THREAD

**Issue by sneumann** [mwang87/MetabolomicsSpectrumResolver#100]
Hi,
for https://metabolomics-usi.ucsd.edu/json/?usi=mzspec:MASSBANK:EQ325301
you get a nice JSON, but for (inexistent) https://metabolomics-usi.ucsd.edu/json/?usi=mzspec:MASSBANK:EQ32530X you get an `500 Internal Server Error` page.

1) That is not valid JSON :-) 
2) Maybe the return value should be a `404 Not Found` if the target does not exist. 

Yours,
Steffen

**Comment by mwang87** [comment]
Great catch @sneumann! We'll get it fixed in the next release.

**Comment by bittremieux** [comment]
When using the new style USIs implemented in PR #88 the error message will be more informative.
![image](https://user-images.githubusercontent.com/10773123/88090401-63bf8f80-cb42-11ea-88c1-ca9e2c387931.png)
