### ISSUE TITLE
Potential: coloring labeled peaks so its clear what we're pointing to

### ISSUE THREAD

**Issue by mwang87** [mwang87/MetabolomicsSpectrumResolver#11]

**Comment by bittremieux** [comment]
It's not really part of the public API, but annotated peaks can be colored using `spectrum_utils` by overwriting the `colors` dict in `spectrum_utils.plot`.

Specifically:

```
import spectrum_utils.plot as sup
sup.colors['unknown'] = '#000000'  # Color HEX code.
```

**Comment by bittremieux** [comment]
I've added some documentation about this: https://spectrum-utils.readthedocs.io/en/latest/plotting.html#peak-colors
