### ISSUE TITLE
Mirror plots of spectral library matches

### ISSUE THREAD

**Issue by mwang87** [mwang87/MetabolomicsSpectrumResolver#12]
Example URI

https://metabolomics-usi.ucsd.edu/mirror/?usi1=mzspec:MS2LDATASK-38:document:43062&usi2=mzspec:MS2LDATASK-38:document:43062

**Comment by mwang87** [comment]
Prototype working in branch. Does not include labeling of peaks or rescaling. Will wait on Wout's contributions to refactor to make it happen.

**Comment by sdrogers** [comment]
not on the server though now, right?

**Comment by mwang87** [comment]
Not quite yet! PR is work in progress:

https://github.com/mwang87/MetabolomicsSpectrumResolver/pull/13

**Comment by mwang87** [comment]
Merged in:

https://github.com/mwang87/MetabolomicsSpectrumResolver/pull/21

Closing.
