### ISSUE TITLE
Adding a minimum intensity threshold to the fragment ion list

### ISSUE THREAD

**Issue by lfnothias** [mwang87/MetabolomicsSpectrumResolver#132]
Adding a minimum intensity threshold to the fragment ion list would help to summarise the significant fragment ions. It could be either relative or/and absolute.

**Comment by bittremieux** [comment]
I'm going to close this, as you can relatively easily do this by ordering the fragment table by intensity and then selecting the relevant peaks. If there's enough interest for a one-click solution we can revisit this in the future.
