### ISSUE TITLE
Adding a threshold to label fragment ions

### ISSUE THREAD

**Issue by lfnothias** [mwang87/MetabolomicsSpectrumResolver#133]
Adding a threshold to label fragment ions. It could be absolute or/and relative intensity.

**Comment by bittremieux** [comment]
You can order the fragment table be increasing/decreasing intensity and then manually select the corresponding peaks for labeling. Basically you'd like a one-click option to do that?

The same mostly goes for #132, which is pretty similar and also just requires you to order the fragment table by intensity.
