### ISSUE TITLE
Dragging the plot to zoom in/out or other control

### ISSUE THREAD

**Issue by lfnothias** [mwang87/MetabolomicsSpectrumResolver#134]
For zooming in, dragging with the mouse left or right seems the most intuitive way.
For zooming out, mouse double clic would be nice. Or some other shortcuts.
Using the arrows to scale up/down the axis could be helpful as well.

**Comment by bittremieux** [comment]
Unfortunately impossible with static SVG images. That's why we have the m/z and intensity controls instead.
