### ISSUE TITLE
Linking back to the source library page

### ISSUE THREAD

**Issue by lfnothias** [mwang87/MetabolomicsSpectrumResolver#14]
Displaying a link to the source library page.

**Comment by sdrogers** [comment]
do you mean the url that was used to retrieve the data, or something that leads to a more useful URL?

**Comment by laserc** [comment]
Placeholder in Line 26 in spectrum.html 
Needs href link for the source library
@mwang87

**Comment by mwang87** [comment]
Handled here: https://github.com/mwang87/MetabolomicsSpectrumResolver/pull/50

**Comment by mwang87** [comment]
Merged. Closing.
