### ISSUE TITLE
[Bug] Not Resolving

### ISSUE THREAD

**Issue by mwang87** [mwang87/MetabolomicsSpectrumResolver#140]
mzspec:GNPSTASK16d50fb5de564636964680ad8c037b7c:spectra/specs_ms.mgf:scan:827

From this paper:

http://www.rsc.org/suppdata/d0/mo/d0mo00084a/d0mo00084a1.pdf

**Comment by bittremieux** [comment]
This old-style USI is missing the hyphen between `TASK` and the task ID.

Working USI: [`mzspec:GNPSTASK-16d50fb5de564636964680ad8c037b7c:spectra/specs_ms.mgf:scan:827`](https://metabolomics-usi.ucsd.edu/spectrum/?usi=mzspec:GNPSTASK-16d50fb5de564636964680ad8c037b7c:spectra/specs_ms.mgf:scan:827)
