### ISSUE TITLE
Proteomics Support

### ISSUE THREAD

**Issue by mwang87** [mwang87/MetabolomicsSpectrumResolver#143]
1. Fragment Tolerance
2. ProForma Support
3. Neutral Losses Optional

**Comment by mwang87** [comment]
Examples: 

1. mzspec:PXD000966:CPTAC_CompRef_00_iTRAQ_05_2Feb12_Cougar_11-10-09.mzML:scan:12298:[UNIMOD:214]-LHFFM[UNIMOD:35]PGFAPLTSR/2
2. mzspec:PXD000966:CPTAC_CompRef_00_iTRAQ_05_2Feb12_Cougar_11-10-09.mzML:scan:12298:[+144.102063]-LHFFM[+15.994915]PGFAPLTSR/3

**Comment by mwang87** [comment]
Here is API for ProForma Resolution:

http://massive.ucsd.edu/ProteoSAFe/ProteomicsServlet?function=convertproforma&sequence=T%2B42LTPIIQEYFEHGDTNEVAEMLR

**Comment by bittremieux** [comment]
What do you mean with point 3?

**Comment by mwang87** [comment]
> What do you mean with point 3?

Oh if we want to show neutral loss annotations, that is a nice to have, not necessary to have feature.
