### ISSUE TITLE
[Bug] Resolving Some MassBank Accessions

### ISSUE THREAD

**Issue by mwang87** [mwang87/MetabolomicsSpectrumResolver#198]
https://metabolomics-usi.gnps2.org/dashinterface/?usi=mzspec%3AMASSBANK%3A%3Aaccession%3AMSBNK-Keio_Univ-KO001261

**Comment by mwang87** [comment]
Reported by @Adafede

**Comment by Michael-C-Strobel** [comment]
Just ran into this issue. This [line](https://github.com/mwang87/MetabolomicsSpectrumResolver/blob/0355c376bc94995054e74ff6c409262fc8411318/metabolomics_spectrum_resolver/parsing.py#L418) seems to be the culprit.

Changing it to the following should work:
```
 massbank_accession = re.match(
        r"MSBNK-[A-z0-9_]{1,32}-([A-Za-z0-9_]{1,64})", index
    )
```
Let me know and I can submit a PR if that would be helpful.

**Comment by bittremieux** [comment]
That would be great! Thanks.
