### ISSUE TITLE
Tools should return precursor_mz

### ISSUE THREAD

**Issue by sdrogers** [mwang87/MetabolomicsSpectrumResolver#26]
API calls should return (where possible) precursor_mz for spectral alignment...

**Comment by mwang87** [comment]
I've added small bits here and there as part of the spectrum dict returned. If not present, setting to 0. Will begin to add to other API endpoints. GNPS one will require slight update to API return to actually have the precursor mz in the data.

**Comment by mwang87** [comment]
- [ ] GNPS Libraries
- [ ] MS2LDA
- [ ] GNPS Task Spectra
- [ ] Massbank

**Comment by bittremieux** [comment]
Precursor m/z for Massbank included in PR #46.

**Comment by bittremieux** [comment]
Final precursor information for GNPS task spectra fixed in #94.
