### ISSUE TITLE
Different colour for precursor mz

### ISSUE THREAD

**Issue by sdrogers** [mwang87/MetabolomicsSpectrumResolver#28]
In the plot_precursor branch we can use the parameter plot_precursor to add the precursor to the plot. Be good if this could be in a different colour.

I tried this:

```python
import spectrum_utils.plot as sup
sup.colors['unknown'] = '#000000'  # Color HEX code.
```

but got the error that sup didn't have an attribure 'colors'..?

**Comment by bittremieux** [comment]
Hmm, that's very weird. Which version of spectrum_utils are you using?

**Comment by bittremieux** [comment]
I've described this in the spectrum_utils documentation now as well: https://spectrum-utils.readthedocs.io/en/latest/plotting.html#peak-colors

I've verified that it works the way it should, so I'm confused that it doesn't work for you.
