### ISSUE TITLE
Error messages!

### ISSUE THREAD

**Issue by sdrogers** [mwang87/MetabolomicsSpectrumResolver#31]
Useful error messages...

**Comment by sdrogers** [comment]
https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-vii-error-handling

**Comment by bittremieux** [comment]
@sdrogers Did you maybe forget to include the `500.html` template file?

**Comment by sdrogers** [comment]
Whoops...I did....its there now

**Comment by mwang87** [comment]
@sdrogers Is the 500 page ready to be merged back in?

**Comment by sdrogers** [comment]
I think so, but we haven’t yet got it to display sensible errors...

Simon Rogers
simon.d.rogers@gmail.com

**Comment by mwang87** [comment]
Cool! Lets merge it in and I'll put a placeholder error message.

**Comment by mwang87** [comment]
Added standard placeholder error message. We'll figure out real ones soon.
