### ISSUE TITLE
Errors number 2...

### ISSUE THREAD

**Issue by sdrogers** [mwang87/MetabolomicsSpectrumResolver#42]
GNPS mol net jobs: if an incorrect job ID is provided, the service appears to return something that is then interpreted as 0 peaks (i.e. no error is thrown)...Ming : best way to fix? In mol networking, or detecting the zero length at our end?

Part 2: make the error page look nicer (do when contributors page is updated to match styling)

**Comment by mwang87** [comment]
I think for GNPS tasks we can test if the task is a valid task. If not, we then we throw up a specific error saying that. This would entail hitting another GNPS end point before getting the actual spectra.

**Comment by sdrogers** [comment]
Ok, cool. Will leave that with you

**Comment by bittremieux** [comment]
Right now minimal to no error checking is done, we can be much more robust on that front. Check whether the USI is correctly formatted, check whether the spectra exist in their respective resources, handle timeouts, ...

**Comment by sdrogers** [comment]
Agree. Will add a new issue...
