### ISSUE TITLE
MTBLS / Metabolomics Workbench parsing correct?

### ISSUE THREAD

**Issue by bittremieux** [mwang87/MetabolomicsSpectrumResolver#45]
Is the parsing code for MTBLS and Metabolomics Workbench correct? Those functions are identical and query MassIVE instead of those two resources.

**Comment by mwang87** [comment]
Yes, MTBLS we could not find a resource to get the spectra but in MassIVE we have imported all the datasets we think had MSMS so we could do the indirect lookup there.

**Comment by bittremieux** [comment]
And that's also the case for Metabolomics Workbench? The home page doesn't have an example spectrum for those two resources, so I couldn't check whether they work or not.
