### ISSUE TITLE
Error checking

### ISSUE THREAD

**Issue by sdrogers** [mwang87/MetabolomicsSpectrumResolver#47]
Perform proper error checking for each source:

- [x] top-level USI checking (does it match any patterns) - i.e. if we get through the checks and we didn't match it to any source
- [x] MS2LDA - SR to do
- [x] MotifDB - SR to do
- [x] GNPS task
- [x] GNPS library spectrum
- [x] MassBank

and finally

- [x] timeouts

**Comment by sdrogers** [comment]
ms2lda now returns an "error" field in the "json" which we can display....

**Comment by bittremieux** [comment]
USI error checking added in #88.

TODO: timeout handling.
