### ISSUE TITLE
[BUG] Memory Leak

### ISSUE THREAD

**Issue by mwang87** [mwang87/MetabolomicsSpectrumResolver#49]
Every time we open a page the amount of memory the web server uses increases by around 10 MB, and does not go down.

**Comment by sdrogers** [comment]
Weird - had a similar problem with django in debug mode a while back...I wonder if they’re related??

**Comment by bittremieux** [comment]
There might be a memory leak in spectrum_utils. Some quick tests show a difference in Numba allocations and deallocations:
```nrt_mstats(alloc=9, free=7, mi_alloc=7, mi_free=5)```
I'll need to investigate further.

**Comment by bittremieux** [comment]
Never mind, I wasn't properly accounting for method scopes when I was checking those allocations and deallocations. So I don't think it's something in spectrum_utils right now.

**Comment by bittremieux** [comment]
Matplotlib figures weren't being closed after they were plotted, that's fixed now in #51. I'm not sure whether this will make a big difference for the memory leak, but it won't hurt.
