### ISSUE TITLE
Adding a title for the spectrum

### ISSUE THREAD

**Issue by lfnothias** [mwang87/MetabolomicsSpectrumResolver#5]
Something like:
MS/MS spectrum of m/z 589.19 (scan = 100) - Orbitrap - UNI ID

**Comment by schymane** [comment]
That's quite long, but irrespective masses should be at least 4dp for Orbis, but the title should be as compact but informative as possible, substance name is good if short, if the text is searchable then bits of information should be separated in a way that's consistent, easily parsed and queried if possible ...

**Comment by sdrogers** [comment]
This is all doable, but we might need to specify what information we want from each data source, as they will all store different things. For the tools we maintain (GNPS, MS2LDA, etc) it would be easy enough to get the API to add a "title" key to the json and then just render this?

**Comment by sdrogers** [comment]
Just noticed that Ming has done massbank already...so if, e.g. the masbank API served a 'title' string as part of he data structure then we could render that easy peasy. I could add something for MS2LDA and motifdb...and I reckon pecursor m/z etc could be easily extracted from the massive records...

**Comment by schymane** [comment]
Otherwise a simple default is also "just" the spectral identifier ... might be a back up if no title available, as one can always use this to find the other info ...

**Comment by mwang87** [comment]
Perhaps we could list the spectrum identifier at the bottom if we can come up with a better title based on the resource?
