### ISSUE TITLE
[Linking] Linking from MassBank

### ISSUE THREAD

**Issue by mwang87** [mwang87/MetabolomicsSpectrumResolver#62]

**Comment by mwang87** [comment]
Hey@schymane ! I was wondering if you know if you all would be interested (and easily feasible) to link to the metabolomics-usi page (e.g. https://metabolomics-usi.ucsd.edu/spectrum/?usi=mzdata:MASSBANK:BSU00002) to help users draw vector versions of the spectra for publication. We're planning on rolling out more links within GNPS and MS2LDA (already have it from results from GNPS). We think its relatively nice and thank you so much for the feedback so far. We're already linking back to the parent resource so hopefully it'll help connect people with the data! Let us know!

**Comment by schymane** [comment]
@sneumann @tsufz @sdrogers let's discuss while at Dagstuhl

**Comment by sneumann** [comment]
Is there any documentation ? Or is it as simple as adding a URL 
`<a href="https://metabolomics-usi.ucsd.edu/spectrum/?usi=mzdata:MASSBANK:$ACCESSION">Additional visualisation</a>`
to the Record JSP rendering page near the spectrum ? Yours, Steffen

**Comment by mwang87** [comment]
@sneumann Yes, apologies for the lack of documentation, i'll add a bit, but it is that easy.

**Comment by schymane** [comment]
Hi @mwang87 out on a tangent: would it be possible to resolve by splash?

**Comment by sneumann** [comment]
ok, @meier-rene is the expert. I quickly hacked into 
https://github.com/MassBank/MassBank-web/blob/master/MassBank-Project/MassBank/src/main/webapp/RecordDisplay.jsp#L555
to do 
```
<tr>
<td><a href="https://metabolomics-usi.ucsd.edu/spectrum/?usi=mzdata:MASSBANK:<%=accession%>">Additional visualisation</a></td>
</tr>
```
Which will give you https://msbi.ipb-halle.de/MassBank/RecordDisplay.jsp?id=PS004505&dsn=RIKEN_ReSpect
Will now create a pull request for MassBank. Yours, Steffen

**Comment by sneumann** [comment]
@schymane : SPLASH is tracked in https://github.com/mwang87/MetabolomicsSpectrumResolver/issues/66

**Comment by meier-rene** [comment]
Thank you for the PR. Its rolled out to the dev server https://msbi.ipb-halle.de/MassBank. Closing.
