### ISSUE TITLE
[Mirror Plot] Embed spectral similarity score calculation

### ISSUE THREAD

**Issue by mwang87** [mwang87/MetabolomicsSpectrumResolver#65]
As @sdrogers had previously mentioned, we should just provide a standardized way for people to align spectra and give out a cosine score, with matches peaks and all that jazz. 

Future idea, simple to implement but not necessary for manuscript

**Comment by bittremieux** [comment]
Something like this?

![16861_unshifted](https://user-images.githubusercontent.com/10773123/73227635-fb5e9b00-4128-11ea-8110-5865f7c8211a.png)

I've got most of that code already, so it should be pretty easy to implement.

**Comment by mwang87** [comment]
Yeah, exactly! That score we would embed into the match. Then at least people have a reference implementation across different analysis platforms. Would be good if it matched what we did at GNPS but not a necessity. People will naturally ask for more things like tolerances and all that jazz, but thats V2.

**Comment by sdrogers** [comment]
Is it able to show a shifted match?

Simon Rogers
simon.d.rogers@gmail.com

**Comment by bittremieux** [comment]
I have code to compute shifted matches, but it's a C++ extension, so maybe not super convenient. It works though.

**Comment by mwang87** [comment]
@sdrogers I think that would be a great addition I think we talked about before. Lets play with it, and for v1 of this perhaps we could just include exact match for now?

**Comment by sdrogers** [comment]
Agree — exact for now. I have python for the shifted for later...

Simon Rogers
simon.d.rogers@gmail.com
