### ISSUE TITLE
[New Feature] Link from SPLASH

### ISSUE THREAD

**Issue by sneumann** [mwang87/MetabolomicsSpectrumResolver#66]
Hi, it would be great to have SPLASH support, which would be independent of the spectral database.
This would be useful if a paper or resource specifies a reference spectrum via its SPLASH.
An example could be:
https://metabolomics-usi.ucsd.edu/spectrum/?usi=mzdata:SPLASH:splash10-0002-0900000000-f236794b68cee8f6798c
This would only work for spectra that are indexed through their SPLASH, and might initially only be feasible for e.g. reference spectra. Yours, Steffen

**Comment by mwang87** [comment]
Lets prototype it! I think its a good idea. Might not be ready for first version of the manuscript, but is a v2 feature!

Ming

**Comment by schymane** [comment]
I think this would be great ... it would allow us theoretically resource-independent plotting ... definitely a +1 my side for this feature ...

**Comment by mwang87** [comment]
Going to implement first version of this where we calculate the SPLASH and display it. In the long run, as this relationship between SPLASH and USI builds up, we can resolve back and forth! 

To start off with, I will hit all GNPS and MASSBANK library spectra if feasible to make an initial stab at populating the database.

**Comment by schymane** [comment]
MassBank.EU spectra should already have a SPLASH in the records (but GNPS too, right?)

**Comment by mwang87** [comment]
Yes, definitely do, Just want to automatically get peaks and generate to show proof of principle. Also, easier implementation wise to just let the system handle everything and data ingress in a single code path. We'll see! Sorry if I hit MassBank.EU servers super hard.

**Comment by sneumann** [comment]
Hi, @tsufz will have an eye on system load (any ETA when that might happen ?). 
Also, you could grab all records via `git clone https://github.com/MassBank/MassBank-data.git`. 
Yours, Steffen
