### ISSUE TITLE
[Documentation] mzspec vs. mzdata

### ISSUE THREAD

**Issue by sneumann** [mwang87/MetabolomicsSpectrumResolver#67]
Hi, is there any information about the difference between the `mzspec:` and `mzdata:` prefix in https://github.com/mwang87/MetabolomicsSpectrumResolver/blob/master/README.md#example-usi-urls ? IIRC the Proteomics USI only knows `mzspec:`. Yours, Steffen

**Comment by mwang87** [comment]
Oh yes, I think that is a typo on our end. Everything shoudl be mzspec. We actually just ignore the first block when we parse.
