### ISSUE TITLE
[MS2LDA] Change in permissions

### ISSUE THREAD

**Issue by mwang87** [mwang87/MetabolomicsSpectrumResolver#73]
@sdrogers Was there a change on the MS2LDA.org side. 

One test we had: 

https://metabolomics-usi.ucsd.edu/spectrum/?usi=mzspec:MS2LDATASK-38:document:43062

Seems to be refused by the server:

{'error': 'This feature only works for public experiments'}

**Comment by sdrogers** [comment]
Hi Ming,
Yes — sorry, didn’t realise that that was the test one.
I realised that this made a bit of a back-door into data that was potentially not public, so now it only works for public experiments…
This would be a better test:
mzspec:MS2LDATASK-190:document:270684
Simon
Simon Rogers
simon.d.rogers@gmail.com

**Comment by mwang87** [comment]
Awesome, merged into tests and deployed.
