### ISSUE TITLE
Bug fragment ions not labeled

### ISSUE THREAD

**Issue by lfnothias** [mwang87/MetabolomicsSpectrumResolver#76]
In the following spectrum, two intense fragment ions at mz 205 and 321 don't want to get labelled.

https://metabolomics-usi.ucsd.edu/spectrum/?usi=mzspec:GNPSTASK-9ce6f26388bc491ba3439e03df9d038d:spectra/specs_ms.mgf:scan:25577

**Comment by bittremieux** [comment]
That's just part of our heuristic labeling function; only a single peak per small m/z interval is labeled to avoid overly cluttered figures. Those two peaks at 205 and 321 don't get labeled because there are more intense peaks in the same interval at 188 and 339.

**Comment by lfnothias** [comment]
Ideally, I think that heuristic should be modifiable by the user. Because in some case, like this one,  we want to have more peaks labeled and they should be viewable by changing the font size.
