### ISSUE TITLE
Showing the precursor ion mass somewhere on the header/figure

### ISSUE THREAD

**Issue by lfnothias** [mwang87/MetabolomicsSpectrumResolver#77]
Showing the precursor ion mass somewhere on the header/figure.

**Comment by bittremieux** [comment]
The precursor m/z is included in the header when it's known, see for example: https://metabolomics-usi.ucsd.edu/spectrum/?usi=mzspec:GNPSLIBRARY:CCMSLIB00005436077

Precursor m/z isn't available yet for GNPS task spectra: #26
