### ISSUE TITLE
Is cosine similarity working correctly?

### ISSUE THREAD

**Issue by sdrogers** [mwang87/MetabolomicsSpectrumResolver#78]
This example is a bit baffling:
https://metabolomics-usi.ucsd.edu/mirror/?usi1=mzspec:MASSBANK:PB000417&usi2=mzspec:MS2LDATASK-1198:document:1628659
Any thoughts?

**Comment by bittremieux** [comment]
The problem seems to be that peak matching is greedy. So in this case the base peak at 188 in one spectrum is matched to a very small peak that's within the m/z tolerance as well.

I'll fix it later today (hopefully).
