### ISSUE TITLE
[New feature] ms2 tolerance configurable for mirror

### ISSUE THREAD

**Issue by sdrogers** [mwang87/MetabolomicsSpectrumResolver#82]
Noticed TODO in code - this would be v useful...

**Comment by sdrogers** [comment]
Best way to make a new `drawing_controls.html` and `get_drawing_controls()` method specifically for mirror plotting? Easiest way to do so without duplication? Two forms?

**Comment by bittremieux** [comment]
Rather than duplicate the `drawing_controls.html` entirely, maybe it can work by adding a macro there to add additional options? But the JavaScript to submit the parameters need to be extended somehow as well.
