### ISSUE TITLE
SVG Drawing Options Interface

### ISSUE THREAD

**Issue by mwang87** [mwang87/MetabolomicsSpectrumResolver#9]
- mass range filter
- labels on/off
- emma slant
- minimum peak intensity for label

**Comment by sdrogers** [comment]
so, a little form on the page...with a 'refresh' button?
Would be nice...

**Comment by mwang87** [comment]
exactly, give me 10 min, will push something out.

**Comment by mwang87** [comment]
OK a bit more complicated in making bootrap behave, first version deployed:

http://mingwangbeta.ucsd.edu:5087/spectrum/?usi=mzdata:MASSBANK:AC000372

**Comment by mwang87** [comment]
Added download buttons.

**Comment by sdrogers** [comment]
nice! Would be neat for it to provide the new usi url that will make this image?
Which reminds me, I'm not sure the additional plot arguments work in the main spectrum page? Just checked: they don't. I'll fix that....

**Comment by mwang87** [comment]
Cool, I'll let @sdrogers address the URL update and ability to pull url parameters for drawing.

**Comment by mwang87** [comment]
Will address UI improvements for displaying the rendering controls nicely on multiple screen sizes

**Comment by mwang87** [comment]
@laserc Addressed issues and made it look way nicer. Deployed live.
