### ISSUE TITLE
Make cosine optional in mirror

### ISSUE THREAD

**Issue by sdrogers** [mwang87/MetabolomicsSpectrumResolver#98]
Related to #82 
In use, I've noticed that I sometimes see vastly different cosine scores that I have calculated myself, due to differences in the ms2 tolerance. #82 describes making these parameters in the system. Could we also just switch the cosine on and off? If someone uses a completely different approach to computing cosine, they will likely never be able to reproduce the score we provide, which will look weird in a publication...

**Comment by mwang87** [comment]
I agree, let me make a selection for it, as well as a custom way to edit the title. I think that would help. in the long run having the parameters for the alignment would be grea,t but this is a good stop gap to make it more usable.

**Comment by mwang87** [comment]
I think this is pretty high priority as it makes it seems like we're totally screwing it up.
